# Generated by Django 4.2.7 on 2026-03-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram chat ID (numeric)', null=True),
        ),
    ]
