# Generated by Django 4.2.7 on 2026-03-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram username (@username)', max_length=100),
        ),
    ]
